name: frontend CI # Workflow ì´ë¦„

# í•˜ê¸° ë‚´ìš©ì— í•´ë‹¹í•˜ëŠ” ì´ë²¤íŠ¸ ë°œìƒ ì‹œ github action ë™ì‘
on:
  push: # ëª¨ë“  ë¸Œëœì¹˜ì—ì„œ pushê°€ ì¼ì–´ë‚¬ì„ ë•Œ github action ë™ì‘
    branches:
      - '*'
  pull_request: # ëª¨ë“  ë¸Œëœì¹˜ì—ì„œ PRì´ ì¼ì–´ë‚¬ì„ ë•Œ github action ë™ì‘
    branches:
      - '*'
    types: [ labeled ]

# ì°¸ê³ ì‚¬í•­
# pushê°€ ì¼ì–´ë‚œ ë¸Œëœì¹˜ì— PRì´ ì¡´ì¬í•˜ë©´, pushì— ëŒ€í•œ ì´ë²¤íŠ¸ì™€ PRì— ëŒ€í•œ ì´ë²¤íŠ¸ ëª¨ë‘ ë°œìƒí•©ë‹ˆë‹¤.

jobs:
  build:
    if: ${{ github.event.label.name == 'ğŸ§‘ğŸ»â€ğŸ’» í”„ë¡ íŠ¸ì—”ë“œ' }}
    runs-on: ubuntu-22.04 # ì‹¤í–‰ í™˜ê²½ ì§€ì •

    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v2

      - name: Check Node v # Node v í™•ì¸
        run: node -v

      - name: Install Dependencies # ì˜ì¡´ íŒŒì¼ ì„¤ì¹˜
        working-directory: ./frontend
        run: yarn install

      - name: Dev Build # React Dev Build
        working-directory: ./frontend
        run: yarn build-dev

      - name: Prod Build # React Prod Build
        working-directory: ./frontend
        run: yarn build-prod
        
